name: Fly Production Deploy
on:
  push:
    tags:
      - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Test
        run: ENV=.env.test go test -v ./...
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Create fly.toml
        run: echo "${{ secrets.FLY_PRD }}" > fly.toml
      - name: Fly deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
